# Exported from Render on 2026-04-27T17:45:11Z
version: "1"
projects:
- name: geoyield
  environments:
  - name: Production
    services:
    - type: web
      name: geoyield-blueprint
      runtime: python
      repo: https://github.com/carlos-fernandez-ruiz/pontia-mlops-tutorial-grupo5
      plan: free
      envVars:
      - key: GITHUB_REPO
        value: carlos-fernandez-ruiz/pontia-mlops-tutorial-grupo5        
      region: frankfurt
      buildCommand: pip install -r requirements.txt
      startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8080
      autoDeployTrigger: commit
      rootDir: deployment