services:

  postgis:
    # se utiliza la imagen oficial de postgis, que incluye tanto postgresql como postgis, lo que permite tener una base de datos geoespacial lista para usar sin necesidad de configuraciones adicionales
    image: postgis/postgis:18-master
    container_name: geoyield_db
    env_file:
      - .env # se cargan las variables de entorno desde el archivo .env ubicado en el mismo directorio que el docker-compose.yml, lo que permite configurar fácilmente el usuario, contraseña y base de datos sin necesidad de modificar el docker-compose.yml directamente
    environment:
    # estas variables de entorno son las que se utilizan para configurar la base de datos postgresql, y se corresponden con los valores definidos en el archivo .env, lo que permite una configuración flexible y segura sin necesidad de hardcodear estos valores en el docker-compose.yml
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # la base de datos se expone solo a la red interna de docker, no al host, por eso se usa 'expose' en lugar de 'ports'
    expose:
      - "5432"
    # se monta un volumen para persistir los datos de la base de datos, mapeando al directorio en el contenedor indicado en la documentación oficial de la imagen (dockerhub)
    volumes:
      - geoyield_db:/var/lib/postgresql
    # la api y la base de datos se encuentran ane una red interna tipo bridge para que puedan comunicarse entre sí, pero no estén expuestas al host
    networks:
      - geoyield_net
    # solventa el asunto ya comentado en clase de que al api intenta conectar a la base de datos antes de que esta esté inicializada y lista para aceptar conexiones, lo que provoca errores de conexión
    # con esto se da un periodo de gracia de 30 segundos a partrie de cual se lanzan hasta 5 pings antes de declara la base de datos 'unhealty'
    # se da 5s hasta dar u ping por fallido y se reintentan cada 10s, lo que da un margen de hasta 1 minuto para que la base de datos esté lista antes de que el api deje de intentar conectar
    healthcheck:
      test: ["CMD", "geoyield", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api: 
    # la imagen se construye a partir del Dockerfile ubicado en el mismo directorio que el docker-compose.yml, lo que permite incluir todas las dependencias necesarias para ejecutar el api, incluyendo el conector de mariadb para python
    build: ./
    container_name: geoyield_api
    env_file:
      - .env # se cargan las variables de entorno desde el archivo .env ubicado en el mismo directorio que el docker-compose.yml, lo que permite configurar fácilmente la cadena de conexión a la base de datos sin necesidad de modificar el docker-compose.yml directamente
    # se expone al host en el puerto 8080, mapeando al puerto 8000 del contenedor donde se ejecuta el api, lo que permite acceder al api desde el host a través de localhost:8080
    ports:
      - "8080:8000"
    # cadena de conexión en base a documentación. Ver valores de las variables de entorno de MARIADB_USER y MARIADB_PASSWORD en el servicio de mariadb
    # el puerto en la red interna es siempre el del contendor
    volumes:
      - geoyield_log:/logs
      - geoyield_metrics:/metrics
    # environment: las variables de entorno se cargan en main.py a través de load_dotenv(), por lo que no es necesario definirlas aquí
    networks:
      - geoyield_net
    depends_on:
      postgis:
        # solventa el problema de que el api intente conectar a la base de datos antes de que esta esté inicializada y lista para aceptar conexiones, lo que provoca errores de conexión
        condition: service_healthy

# son volumenes de docker, no se mapean a directorios del host, lo que permite que docker gestione la persistencia de los datos sin necesidad de preocuparse por la estructura de directorios del host, y también evita problemas de permisos que pueden surgir al mapear volúmenes a directorios del host
# si se hubiesen mapeado a directorios del host, habría que asegurarse de que esos directorios existen y tienen los permisos adecuados antes de iniciar los contenedores, lo que añade complejidad a la configuración y despliegue
volumes:
  geoyield_db:
  geoyield_logs:

networks:
  geoyield_net:
    driver: bridge

 
